name: Deploy Pipeline

on:
  push:
    branches: [ main ]

jobs:
  trigger-build:
    uses: devopsbyraham/github-node-repo-PNXR/.github/workflows/main.yml@main
    with:
      node-version: '20'
    secrets:
      API_TOKEN: ${{ secrets.PROD_API_TOKEN }}
