name: NODE-JS

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: install dependencies
        run: npm install # Changed from 'npm ci' since no package-lock.json exists

      - name: run
        run: npm run build --if-present

      - name: test
        run: echo "test is passed"

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nodejs-artifact
          path: |
          package*
