name: NODE-JS

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v7

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: install dependencies
        run: npm install

      - name: run
        run: npm run build --if-present

      - name: test
        run: echo "test is passed"

